version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Pa$$w0rd
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

volumes:
  dbdata: